apiVersion: v1
kind: Secret
metadata:
  name: featureflags-secrets
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.env.databaseUrl | quote }}
  REDIS_PASSWORD: {{ .Values.env.redisPassword | quote }}
